/**
 * FixturesController
 */

var servers = [ { name: "StudMine",
                  address: "studmine.fr",
                  version: "1.7.5",
                  key: "studmine",
                  size: 64 },
                { name: "CraftBox",
                  address: "craftbox.fr",
                  version: "1.7.2",
                  key: "craftbox",
                  size: 25 },
                { name: "BoxCraft",
                  address: "boxcraft.fr",
                  version: "1.7.3",
                  key: "boxcraft",
                  size: 30 },
                { name: "Desticraft",
                  address: "desticraft.fr",
                  version: "1.7.5",
                  key: "desticraft",
                  size: 128 },
                { name: "The Craft",
                  address: "thecraft.fr",
                  version: "1.7.5",
                  key: "thecraft",
                  size: 128 },
                { name: "Historycraft",
                  address: "historycraft.fr",
                  version: "1.6.1",
                  key: "historycraft",
                  size: 32 },
                { name: "Minefield",
                  address: "minefield.fr",
                  version: "1.7.5",
                  key: "minefield",
                  size: 256 },
                { name: "Heavencraft",
                  address: "heavencraft.fr",
                  version: "1.7.4",
                  key: "heavencraft",
                  size: 20 },
                { name: "Craft Valley",
                  address: "craftvalley.fr",
                  version: "1.7.3",
                  key: "craftvalley",
                  size: 16 },
                { name: "UFB Craft",
                  address: "ufbcraft.fr",
                  version: "1.7.2",
                  key: "ufbcraft",
                  size: 16 }
                  ];
var players = [ {pseudo: 'Hacksore'},
                {pseudo: 'azfanatic11'},
                {pseudo: 'Bensword331'},
                {pseudo: 'C418'},
                {pseudo: 'coolity'},
                {pseudo: 'DarkTwister'},
                {pseudo: 'Derpmeifter'},
                {pseudo: 'eagleeye64000'},
                {pseudo: 'Earstorm'},
                {pseudo: 'Elecpat'},
                {pseudo: 'FemoMadness'},
                {pseudo: 'FoidzaFlow'},
                {pseudo: 'goodthief'},
                {pseudo: 'inacio'},
                {pseudo: 'IrAdz'},
                {pseudo: 'kmlkmljkl'},
                {pseudo: 'kp3'},
                {pseudo: 'leonellus'},
                {pseudo: 'Matoking'},
                {pseudo: 'Miktor'},
                {pseudo: 'MokkaCicc'},
                {pseudo: 'Nerdy'},
                {pseudo: 'Notch'},
                {pseudo: 'Notsuru'},
                {pseudo: 'PertalGad'},
                {pseudo: 'ruarai'},
                {pseudo: 'RussianSpy'},
                {pseudo: 'sade1212'},
                {pseudo: 'Semaru'},
                {pseudo: 'alexgrist'},
                {pseudo: 'TheStabbyBunny'},
                {pseudo: 'zdog101'},
                {pseudo: 'Cellan'},
                {pseudo: 'Foogles'},
                {pseudo: 'Snipex01'},
                {pseudo: 'Mzilla'},
                {pseudo: 'sk8erace1'},
                {pseudo: 'Doomish'},
                {pseudo: 'Alikku'},
                {pseudo: 'johnlmonkey'},
                {pseudo: 'Rulz'},
                {pseudo: 'vexx21322'},
                {pseudo: 'GenericToast'},
                {pseudo: 'Karl_L'},
                {pseudo: 'Krail'},
                {pseudo: 'Camcom25'},
                {pseudo: 'CherryJimbo'},
                {pseudo: 'Kcin'},
                {pseudo: 'Laserpanda'},
                {pseudo: 'Rastadogg'},
                {pseudo: 'Zedo_Mann'},
                {pseudo: 'NeoTyrant'},
                {pseudo: 'MrFoxer'},
                {pseudo: 'deadmau5'},
                {pseudo: 'Woolio1'},
                {pseudo: 'RaxaHax'},
                {pseudo: 'God'},
                {pseudo: 'Inzuki'},
                {pseudo: 'Romaji'},
                {pseudo: 'Whomobile'},
                {pseudo: 'Bletotum'},
                {pseudo: 'Tursikas'},
                {pseudo: 'awwent'},
                {pseudo: 'kraffslol'},
                {pseudo: 'Wirexia'},
                {pseudo: 'Minotour'},
                {pseudo: 'elitechad255'},
                {pseudo: 'war_man333'},
                {pseudo: 'Nesral'},
                {pseudo: 'pyranis'},
                {pseudo: 'csd'},
                {pseudo: 'chrisjon'},
                {pseudo: 'Screek'},
                {pseudo: 'Taizun'},
                {pseudo: 'kyrbi'},
                {pseudo: 'FlamingFury'},
                {pseudo: 'Mielsen'},
                {pseudo: 'Noggin'},
                {pseudo: 'Claush'},
                {pseudo: 'znabela'},
                {pseudo: 'Yunie'},
                {pseudo: 'Mooncowdale'},
                {pseudo: 'Zencraft'},
                {pseudo: 'Pedobuddy'},
                {pseudo: 'trylleklovn'},
                {pseudo: 'hasfeldt'},
                {pseudo: 'DaMoggen'},
                {pseudo: 'Spikespiegel'},
                {pseudo: 'Gravn'},
                {pseudo: 'DarkCybrid'},
                {pseudo: 'Nikmi'},
                {pseudo: 'Tentrillicon'},
                {pseudo: 'Cpt_Universe'},
                {pseudo: 'hoebag89'},
                {pseudo: 'JackHemming'},
                {pseudo: 'frachlitz'},
                {pseudo: 'Gedehamsen'},
                {pseudo: 'scratch_nl'},
                {pseudo: 'Yeojsav'},
                {pseudo: 'TVC'},
                {pseudo: 'Profanwolf'},
                {pseudo: 'TheHANGOVER'},
                {pseudo: 'KneeSlappington'},
                {pseudo: 'rebel1231'},
                {pseudo: 'Lloyder'},
                {pseudo: 'thephuwnaren'},
                {pseudo: 'ohofvictory'},
                {pseudo: 'xpod1'},
                {pseudo: 'AndrewPH'},
                {pseudo: 'swampie'},
                {pseudo: 'blueplastic'},
                {pseudo: 'SkunkGER'},
                {pseudo: 'destroyer058'},
                {pseudo: 'Fredbob'},
                {pseudo: 'reapaninja'},
                {pseudo: 'doodoo123987'},
                {pseudo: 'Afromana'},
                {pseudo: 'Asrue2'},
                {pseudo: 'baroni'},
                {pseudo: 'Skullbreaker283'},
                {pseudo: 'Tomasobst'},
                {pseudo: 'Skoinks'},
                {pseudo: 'Ps360'},
                {pseudo: 'Glent'},
                {pseudo: 'DoritosMan'},
                {pseudo: 'MetallicLion'},
                {pseudo: 'yannickgd'},
                {pseudo: 'ManningQB18'},
                {pseudo: 'Mesquite'},
                {pseudo: 'Conro'},
                {pseudo: 'Glueguy'},
                {pseudo: 'chookenfudd'},
                {pseudo: 'Coestar'},
                {pseudo: 'KillerZombie'},
                {pseudo: 'Master0r0'},
                {pseudo: 'Tark'},
                {pseudo: 'Xorjt'},
                {pseudo: 'hug9000'},
                {pseudo: 'muhammad'},
                {pseudo: 'ellashella'},
                {pseudo: 'Darkauron'},
                {pseudo: 'cskim13'},
                {pseudo: 'Cryolithius'},
                {pseudo: 'PartyPancakes'},
                {pseudo: 'Dwragon'},
                {pseudo: 'crazydev'},
                {pseudo: 'crazy991'},
                {pseudo: 'Herobrine'},
                {pseudo: 'Hypershadsy'},
                {pseudo: 'CrazyJared'},
                {pseudo: 'Alp'},
                {pseudo: 'coopersnow'},
                {pseudo: 'Dragonite24'},
                {pseudo: 'Mongoloid'},
                {pseudo: 'yoshi8710'},
                {pseudo: 'BowlOfSoup'},
                {pseudo: 'Cheeeezzz'},
                {pseudo: 'SunriseMoon'},
                {pseudo: 'Cheapshot'},
                {pseudo: 'Quex'},
                {pseudo: 'Dr_MadMan'},
                {pseudo: 'jeb_'},
                {pseudo: 'Sogo'},
                {pseudo: 'torteela'},
                {pseudo: 'Dapper_Swain'},
                {pseudo: 'barrowsx'},
                {pseudo: 'HellCatcher'},
                {pseudo: 'brandonhare'},
                {pseudo: 'Apptendo'},
                {pseudo: 'Frewp'},
                {pseudo: 'Hoodoo456'},
                {pseudo: 'Caboose2641'},
                {pseudo: 'lordskelzor'},
                {pseudo: 'wolfenstrike'},
                {pseudo: 'Sukor'},
                {pseudo: 'JakeEpps'},
                {pseudo: 'EpicPoodle'},
                {pseudo: 'Darber'},
                {pseudo: 'DTB1996'},
                {pseudo: 'thebiglebowski33'},
                {pseudo: 'Tinter'},
                {pseudo: 'Computrix'},
                {pseudo: 'pro'},
                {pseudo: 'jake'},
                {pseudo: 'Nazilord24'},
                {pseudo: 'fef'},
                {pseudo: 'auntjoemima'},
                {pseudo: 'Concrete'},
                {pseudo: 'dynemo'},
                {pseudo: 'Sgt_Cortez'},
                {pseudo: 'phabeZ'},
                {pseudo: 'Segolia'},
                {pseudo: 'Jakeiswin'},
                {pseudo: 'Masterlegodude'},
                {pseudo: 'metrotyranno'},
                {pseudo: 'DimJim'},
                {pseudo: 'ChauffeR'},
                {pseudo: 'KingSam'},
                {pseudo: 'richard9311'},
                {pseudo: 'iam2little'},
                {pseudo: 'Lassemb'},
                {pseudo: 'Valdrec'},
                {pseudo: 'zedpenguin'},
                {pseudo: 'kubson'},
                {pseudo: 'cyndrasil'},
                {pseudo: 'Trase'},
                {pseudo: 'Fish_Warden'},
                {pseudo: 'Tuxedo'},
                {pseudo: 'phray'},
                {pseudo: 'gawdofrofls'},
                {pseudo: 'N10do64'},
                {pseudo: 'Grimmy423'},
                {pseudo: 'TPmax17'},
                {pseudo: 'liv3d'},
                {pseudo: 'kizzycocoa'},
                {pseudo: 'Earfull'},
                {pseudo: 'Jexeld'},
                {pseudo: 'Scheer'},
                {pseudo: 'Medlir'},
                {pseudo: 'memnoc'},
                {pseudo: 'Auv5'},
                {pseudo: 'Neath'},
                {pseudo: 'Xylic'},
                {pseudo: 'pr0nstar'},
                {pseudo: 'deadmat'},
                {pseudo: 'citricsquid'},
                {pseudo: 'Conan3D'},
                {pseudo: 'rubbersoul420'},
                {pseudo: 'IvanDonat'},
                {pseudo: 'cheater09'},
                {pseudo: 'Spyder638'},
                {pseudo: '_Undefined'},
                {pseudo: 'andersonmat'},
                {pseudo: 'Rixxz2'},
                {pseudo: 'simix10'},
                {pseudo: 'RedPeepin'},
                {pseudo: 'ejonkou'},
                {pseudo: 'xHellfire'},
                {pseudo: 'AdamtheClown'},
                {pseudo: 'cyrkon'},
                {pseudo: 'Genesis343'},
                {pseudo: 'CapnAwesom'},
                {pseudo: 'SolWolf'},
                {pseudo: 'Neogetz'},
                {pseudo: 'Gotcha'},
                {pseudo: 'nox_PHX'},
                {pseudo: 'Elloa'},
                {pseudo: 'Razorlance'},
                {pseudo: 'whatnow'},
                {pseudo: 'Zuriki'},
                {pseudo: 'Dread'},
                {pseudo: 'Majeh'},
                {pseudo: 'Snowman'},
                {pseudo: 'WOOTinator'},
                {pseudo: 'Pledgemonkey'},
                {pseudo: 'McBeeferton'},
                {pseudo: 'Xephos'},
                {pseudo: 'Honeydew'},
                {pseudo: 'Old_Peculier'},
                {pseudo: 'Israphael'},
                {pseudo: 'Israphel'},
                {pseudo: 'Ryzo'},
                {pseudo: 'Skylord_Lysander'},
                {pseudo: 'Swedman'},
                {pseudo: 'jmcneely'},
                {pseudo: 'lolpie24'},
                {pseudo: 'Xkrules'},
                {pseudo: 'Hollure'},
                {pseudo: 'lonewarrior'},
                {pseudo: 'slubub'},
                {pseudo: 'pinguiniv'},
                {pseudo: 'Demonkush'},
                {pseudo: 'Destati'},
                {pseudo: 'raquzzic2'},
                {pseudo: 'sord213'},
                {pseudo: 'Colten'},
                {pseudo: 'CG62'},
                {pseudo: 'mrwormy'},
                {pseudo: 'Agronaut'},
                {pseudo: 'mikeybx'},
                {pseudo: 'Kakarikon'},
                {pseudo: 'Crazyiness'},
                {pseudo: 'power526'},
                {pseudo: 'SlamBamActionman'},
                {pseudo: 'Yoyosorayo'},
                {pseudo: 'thetaco8808'},
                {pseudo: 'kittyinabottle'},
                {pseudo: 'Jakeobs'},
                {pseudo: 'jctitan'},
                {pseudo: 'kbdasoccer'},
                {pseudo: 'Menen'},
                {pseudo: 'A_Big_Rock'},
                {pseudo: 'Fendron'},
                {pseudo: 'robloxx'},
                {pseudo: 'elbowgrease12'},
                {pseudo: 'stolengoose'},
                {pseudo: 'kafder2'},
                {pseudo: 'Fvpm'},
                {pseudo: 'jnr_cckane'},
                {pseudo: 'kelquethas'},
                {pseudo: 'Zakhep'},
                {pseudo: 'mons10'},
                {pseudo: 'elrobto'},
                {pseudo: 'setsunakai'},
                {pseudo: 'doomplayer'},
                {pseudo: 'Pwnage_HenTgen'},
                {pseudo: 'Rooopppi'},
                {pseudo: 'm00gle'},
                {pseudo: 'Stuu'},
                {pseudo: 'T3hdrakkus'},
                {pseudo: 'MrDerogative'},
                {pseudo: 'Goratrixx'},
                {pseudo: 'Swordself'},
                {pseudo: 'Pelleybelley'},
                {pseudo: 'whitenoize'},
                {pseudo: 'groopo'},
                {pseudo: 'Skype'},
                {pseudo: 'CruelNoise'},
                {pseudo: 'Alphasoldier'},
                {pseudo: 'Whitehman'},
                {pseudo: 'Omicron'},
                {pseudo: 'Olidood'},
                {pseudo: 'ryuanesha'},
                {pseudo: 'MiniMatt'},
                {pseudo: 'DolphinTuna'},
                {pseudo: 'GladeGuard'},
                {pseudo: 'IronValley'},
                {pseudo: 'Shadowtex'},
                {pseudo: 's_amroberts'},
                {pseudo: 'Old_Peculiar'},
                {pseudo: 'Alienation25'},
                {pseudo: 'Blaxor'},
                {pseudo: 'Klegg'},
                {pseudo: 'beth'},
                {pseudo: 'Bomber57'},
                {pseudo: 'GoogleChrome'},
                {pseudo: 'lurkercraft'},
                {pseudo: 'Xcronias'},
                {pseudo: 'Googie2149'},
                {pseudo: 'muncher21'},
                {pseudo: 'Rhyno'},
                {pseudo: 'JorgeZ'},
                {pseudo: 'xilefian'},
                {pseudo: 'Manarine'},
                {pseudo: 'steinhaus'},
                {pseudo: 'Grabarz19'},
                {pseudo: 'Gamer027'},
                {pseudo: 'Glass_Miner'},
                {pseudo: 'Insidiea'},
                {pseudo: 'Helgesander'},
                {pseudo: 'InsanityMan'},
                {pseudo: 'Moonie'},
                {pseudo: 'FreezeInc'},
                {pseudo: 'Dostya'},
                {pseudo: 'Mistrale'},
                {pseudo: 'Dowdoon'},
                {pseudo: 'Smurfffff'},
                {pseudo: 'Duh102'},
                {pseudo: 'minemap'},
                {pseudo: 'Woodenwindows'},
                {pseudo: 'SeanNanoware'},
                {pseudo: 'varunax'},
                {pseudo: 'zdragun'},
                {pseudo: 'Milkcooks'},
                {pseudo: 'nickieroonie'},
                {pseudo: 'ComputerMan12'},
                {pseudo: 'Mr_Conner'},
                {pseudo: 'Gabe_Newell'},
                {pseudo: 'crazymonkay'},
                {pseudo: 'modify'},
                {pseudo: 'TheJohan'},
                {pseudo: 'Twilizer5953'},
                {pseudo: 'Daniel_Rogers'},
                {pseudo: 'spiderfrog'},
                {pseudo: 'EleOnAUni'},
                {pseudo: 'MrBix'},
                {pseudo: 'Bites'},
                {pseudo: 'kinglahcrab'},
                {pseudo: 'SenorStab'},
                {pseudo: 'MasterDucky'},
                {pseudo: 'Gamerx123'},
                {pseudo: 'mules'},
                {pseudo: 'Joe'},
                {pseudo: 'daaaaaan'},
                {pseudo: 'iDP'},
                {pseudo: 'HappyHappyMan'},
                {pseudo: 'DwarfWoot'},
                {pseudo: 'puddin1'},
                {pseudo: 'cavo94'},
                {pseudo: 'got_milk4'},
                {pseudo: 'Tawtle'},
                {pseudo: 'stupib'},
                {pseudo: 'Satele'},
                {pseudo: 'GhostlyGob'},
                {pseudo: 'cheetum'},
                {pseudo: 'ssojj'},
                {pseudo: 'The_Noodle'},
                {pseudo: 'Huseeee'},
                {pseudo: 'subtraho'},
                {pseudo: 'horsedrowner'},
                {pseudo: 'WafflesMgee'},
                {pseudo: 'Halofannr1'},
                {pseudo: 'FlashFireSix'},
                {pseudo: 'CowThing'},
                {pseudo: 'GinTheNinja'},
                {pseudo: 'eLIR'},
                {pseudo: 'BearzUnlimited'},
                {pseudo: 'Beavis9563'},
                {pseudo: 'Pyronaught41'},
                {pseudo: 'Wido'},
                {pseudo: 'Eisblut'},
                {pseudo: 'coolkid588'},
                {pseudo: 'Rex_Rex'},
                {pseudo: 'TTsands'},
                {pseudo: 'jakers247'},
                {pseudo: 'Mr_Hedra'},
                {pseudo: 'Clavus'},
                {pseudo: 'Minecrafter12335'},
                {pseudo: 'agnl'},
                {pseudo: 'Nerdrage'},
                {pseudo: '00Fraday00'},
                {pseudo: 'CaptainQuirk73'},
                {pseudo: 'Naut314'},
                {pseudo: 'Zombie_Boss'},
                {pseudo: 'Creeper_Boss'},
                {pseudo: 'Pricex3'},
                {pseudo: 'Divran'},
                {pseudo: 'Ket'},
                {pseudo: 'Astrellon'},
                {pseudo: 'Bisyss'},
                {pseudo: 'scarletbanner'},
                {pseudo: 'bluelive'},
                {pseudo: 'workbench'},
                {pseudo: 'L_NK'},
                {pseudo: 'Striata'},
                {pseudo: 'Gabbeh'},
                {pseudo: 'mendo89'},
                {pseudo: 'valakut'},
                {pseudo: 'nakedlightbulbs'},
                {pseudo: 'masterbetty'},
                {pseudo: 'prichards'},
                {pseudo: 'atliax'},
                {pseudo: 'drtaru'},
                {pseudo: 'adnan252'},
                {pseudo: 'nikondork'},
                {pseudo: 'OttoKatz'}];
var serversID = [];
var playersID = [];
var createServers = function(serverKey, callback) {
  Server.create(servers[serverKey]).exec(function(err, server) {
    if(err) { console.log(err) }
    serversID[serverKey] = server.id;
    serverKey += 1;
    if(serverKey < servers.length) {
      createServers(serverKey, callback);
    }
    else {
      console.log("Server collection populated !");
      createPlayers(0);
    }
  });
};

var createPlayers = function(playerKey, callback) {
  Player.create(players[playerKey]).exec(function(err, player) {
    if(err) { console.log(err) }
    playersID[playerKey] = player.id;
    playerKey += 1;
    if(playerKey < players.length) {
      createPlayers(playerKey, callback);
    }
    else {
      console.log("Player collection populated !");
      createKills(0);
    }
  });
};

var createKills = function(playerKey, callback) {
  rndKillsCounter = Math.floor((Math.random()*10));
  while(rndKillsCounter > 0) {
    rndVictim = Math.floor((Math.random()*(players.length-1)));
    rndServer = Math.floor((Math.random()*(servers.length-1)));
    Kill.create({killed: playersID[rndVictim], killer: playersID[playerKey], server: serversID[rndServer], weapon: 'SWORD'}).exec(function (err, kill) {
      if(err) { console.log(err) }
    });
    rndKillsCounter--;
  }
  playerKey += 1;
  if(playerKey < players.length) {
    createKills(playerKey, callback);
  }
  else {
    console.log("Kills collection populated !");
    createStats(0);
  }
};

var createStats = function(playerKey, callback) {
  var rndServersCounter = Math.floor((Math.random()*(servers.length-1)));
  while(rndServersCounter > 0) {
    PlayerStat.create({player: playersID[playerKey], server: serversID[rndServersCounter], ratio: 0, timePlayed: Math.floor((Math.random()*604800)), blocksBroken: Math.floor((Math.random()*10000)), blocksPlaced: Math.floor((Math.random()*10000)), levelMax: Math.floor((Math.random()*50)), verbosity: Math.floor((Math.random()*10000)), kills: 0, pvpDeaths: 0, stupidDeaths: Math.floor((Math.random()*1000))}).exec(function (err, stats) {
      if(err) { console.log(err) }
    })
    rndServersCounter--;
  }
  playerKey += 1;
  if(playerKey < players.length) {
    createStats(playerKey, callback);
  }
  else {
    console.log("Stats collection populated !");
    calculate();
  }
};

var calculate = function() {
  Player.find({}).exec(function(err, players) {
    for(playerKey in players) {
      Kill.find({}).exec(function(err, kills) {
        for(killKey in kills) {
          var killer = 0;
          var killed = 0;
          if(kills[killKey].killer === players[playerKey].id) {
            killer++;
          }
          else if(kills[killKey].killed === players[playerKey].id) {
            killed++;
          }
        }
        players[playerKey].ratio = killer/(killed === 0 ? 1 : 0);
        players[playerKey].pvpDeaths = killed;
        players[playerKey].save(function() {
          console.log(players[playerKey]+ " done !");
          console.log(killer+ " killer");
          console.log(killed+ " killed");
        });
      });
    }
    console.log("Calculate stats done");
  });
}

module.exports = {

  // Handle a plugin connection
  populate: function(req, res) {
    createServers(0);

    res.send("Populating the database...<br/>Check your console to be aware of errors");
  },

  /**
   * Overrides for the settings in `config/controllers.js`
   * (specific to APIController)
   */
  _config: {}


};
