/**
 * FixturesController
 */

var servers = [ { name: "StudMine",
                  address: "studmine.fr",
                  version: "1.7.5",
                  key: "studmine",
                  size: 64 },
                { name: "CraftBox",
                  address: "craftbox.fr",
                  version: "1.7.2",
                  key: "craftbox",
                  size: 25 },
                { name: "BoxCraft",
                  address: "boxcraft.fr",
                  version: "1.7.3",
                  key: "boxcraft",
                  size: 30 },
                { name: "Desticraft",
                  address: "desticraft.fr",
                  version: "1.7.5",
                  key: "desticraft",
                  size: 128 },
                { name: "The Craft",
                  address: "thecraft.fr",
                  version: "1.7.5",
                  key: "thecraft",
                  size: 128 },
                { name: "Historycraft",
                  address: "historycraft.fr",
                  version: "1.6.1",
                  key: "historycraft",
                  size: 32 },
                { name: "Minefield",
                  address: "minefield.fr",
                  version: "1.7.5",
                  key: "minefield",
                  size: 256 },
                { name: "Heavencraft",
                  address: "heavencraft.fr",
                  version: "1.7.4",
                  key: "heavencraft",
                  size: 20 },
                { name: "Craft Valley",
                  address: "craftvalley.fr",
                  version: "1.7.3",
                  key: "craftvalley",
                  size: 16 },
                { name: "UFB Craft",
                  address: "ufbcraft.fr",
                  version: "1.7.2",
                  key: "ufbcraft",
                  size: 16 }
                  ];
var players = [ {pseudo: 'Hacksore',
                 online: true},
                {pseudo: 'azfanatic11',
                 online: true},
                {pseudo: 'Bensword331',
                 online: true},
                {pseudo: 'C418',
                 online: false},
                {pseudo: 'coolity',
                 online: false},
                {pseudo: 'DarkTwister',
                 online: true},
                {pseudo: 'Derpmeifter',
                 online: false},
                {pseudo: 'eagleeye64000',
                 online: true},
                {pseudo: 'Earstorm',
                 online: true},
                {pseudo: 'Elecpat',
                 online: true},
                {pseudo: 'FemoMadness',
                 online: false},
                {pseudo: 'FoidzaFlow',
                 online: true},
                {pseudo: 'goodthief',
                 online: false},
                {pseudo: 'inacio',
                 online: false},
                {pseudo: 'IrAdz',
                 online: false},
                {pseudo: 'kmlkmljkl',
                 online: false},
                {pseudo: 'kp3',
                 online: true},
                {pseudo: 'leonellus',
                 online: false},
                {pseudo: 'Matoking',
                 online: false},
                {pseudo: 'Miktor',
                 online: true},
                {pseudo: 'MokkaCicc',
                 online: true},
                {pseudo: 'Nerdy',
                 online: false},
                {pseudo: 'Notch',
                 online: false},
                {pseudo: 'Notsuru',
                 online: true},
                {pseudo: 'PertalGad',
                 online: false},
                {pseudo: 'ruarai',
                 online: false},
                {pseudo: 'RussianSpy',
                 online: true},
                {pseudo: 'sade1212',
                 online: true},
                {pseudo: 'Semaru',
                 online: false},
                {pseudo: 'alexgrist',
                 online: true},
                {pseudo: 'TheStabbyBunny',
                 online: true},
                {pseudo: 'zdog101',
                 online: false},
                {pseudo: 'Cellan',
                 online: false},
                {pseudo: 'Foogles',
                 online: true},
                {pseudo: 'Snipex01',
                 online: false},
                {pseudo: 'Mzilla',
                 online: true},
                {pseudo: 'sk8erace1',
                 online: true},
                {pseudo: 'Doomish',
                 online: false},
                {pseudo: 'Alikku',
                 online: false},
                {pseudo: 'johnlmonkey',
                 online: true},
                {pseudo: 'Rulz',
                 online: true},
                {pseudo: 'vexx21322',
                 online: false},
                {pseudo: 'GenericToast',
                 online: false},
                {pseudo: 'Karl_L',
                 online: true},
                {pseudo: 'Krail',
                 online: true},
                {pseudo: 'Camcom25',
                 online: false},
                {pseudo: 'CherryJimbo',
                 online: true},
                {pseudo: 'Kcin',
                 online: false},
                {pseudo: 'Laserpanda',
                 online: false},
                {pseudo: 'Rastadogg',
                 online: false},
                {pseudo: 'Zedo_Mann',
                 online: true},
                {pseudo: 'NeoTyrant',
                 online: true},
                {pseudo: 'MrFoxer',
                 online: true},
                {pseudo: 'deadmau5',
                 online: false},
                {pseudo: 'Woolio1',
                 online: false},
                {pseudo: 'RaxaHax',
                 online: false},
                {pseudo: 'God',
                 online: false},
                {pseudo: 'Inzuki',
                 online: true},
                {pseudo: 'Romaji',
                 online: true},
                {pseudo: 'Whomobile',
                 online: true},
                {pseudo: 'Bletotum',
                 online: false},
                {pseudo: 'Tursikas',
                 online: true},
                {pseudo: 'awwent',
                 online: true},
                {pseudo: 'kraffslol',
                 online: false},
                {pseudo: 'Wirexia',
                 online: false},
                {pseudo: 'Minotour',
                 online: true},
                {pseudo: 'elitechad255',
                 online: true},
                {pseudo: 'war_man333',
                 online: false},
                {pseudo: 'Nesral',
                 online: true},
                {pseudo: 'pyranis',
                 online: true},
                {pseudo: 'csd',
                 online: true},
                {pseudo: 'chrisjon',
                 online: false},
                {pseudo: 'Screek',
                 online: false},
                {pseudo: 'Taizun',
                 online: true},
                {pseudo: 'kyrbi',
                 online: true},
                {pseudo: 'FlamingFury',
                 online: false},
                {pseudo: 'Mielsen',
                 online: true},
                {pseudo: 'Noggin',
                 online: true},
                {pseudo: 'Claush',
                 online: true},
                {pseudo: 'znabela',
                 online: true},
                {pseudo: 'Yunie',
                 online: true},
                {pseudo: 'Mooncowdale',
                 online: false},
                {pseudo: 'Zencraft',
                 online: false},
                {pseudo: 'Pedobuddy',
                 online: false},
                {pseudo: 'trylleklovn',
                 online: false},
                {pseudo: 'hasfeldt',
                 online: true},
                {pseudo: 'DaMoggen',
                 online: true},
                {pseudo: 'Spikespiegel',
                 online: false},
                {pseudo: 'Gravn',
                 online: false},
                {pseudo: 'DarkCybrid',
                 online: false},
                {pseudo: 'Nikmi',
                 online: false},
                {pseudo: 'Tentrillicon',
                 online: false},
                {pseudo: 'Cpt_Universe',
                 online: false},
                {pseudo: 'hoebag89',
                 online: true},
                {pseudo: 'JackHemming',
                 online: true},
                {pseudo: 'frachlitz',
                 online: false},
                {pseudo: 'Gedehamsen',
                 online: false},
                {pseudo: 'scratch_nl',
                 online: false},
                {pseudo: 'Yeojsav',
                 online: true},
                {pseudo: 'TVC',
                 online: false},
                {pseudo: 'Profanwolf',
                 online: true},
                {pseudo: 'TheHANGOVER',
                 online: true},
                {pseudo: 'KneeSlappington',
                 online: false},
                {pseudo: 'rebel1231',
                 online: false},
                {pseudo: 'Lloyder',
                 online: true},
                {pseudo: 'thephuwnaren',
                 online: true},
                {pseudo: 'ohofvictory',
                 online: false},
                {pseudo: 'xpod1',
                 online: false},
                {pseudo: 'AndrewPH',
                 online: false},
                {pseudo: 'swampie',
                 online: false},
                {pseudo: 'blueplastic',
                 online: false},
                {pseudo: 'SkunkGER',
                 online: true},
                {pseudo: 'destroyer058',
                 online: false},
                {pseudo: 'Fredbob',
                 online: false},
                {pseudo: 'reapaninja',
                 online: false},
                {pseudo: 'doodoo123987',
                 online: true},
                {pseudo: 'Afromana',
                 online: false},
                {pseudo: 'Asrue2',
                 online: true},
                {pseudo: 'baroni',
                 online: false},
                {pseudo: 'Skullbreaker283',
                 online: true},
                {pseudo: 'Tomasobst',
                 online: true},
                {pseudo: 'Skoinks',
                 online: true},
                {pseudo: 'Ps360',
                 online: true},
                {pseudo: 'Glent',
                 online: false},
                {pseudo: 'DoritosMan',
                 online: true},
                {pseudo: 'MetallicLion',
                 online: false},
                {pseudo: 'yannickgd',
                 online: false},
                {pseudo: 'ManningQB18',
                 online: true},
                {pseudo: 'Mesquite',
                 online: false},
                {pseudo: 'Conro',
                 online: true},
                {pseudo: 'Glueguy',
                 online: true},
                {pseudo: 'chookenfudd',
                 online: true},
                {pseudo: 'Coestar',
                 online: false},
                {pseudo: 'KillerZombie',
                 online: true},
                {pseudo: 'Master0r0',
                 online: true},
                {pseudo: 'Tark',
                 online: false},
                {pseudo: 'Xorjt',
                 online: false},
                {pseudo: 'hug9000',
                 online: false},
                {pseudo: 'muhammad',
                 online: true},
                {pseudo: 'ellashella',
                 online: true},
                {pseudo: 'Darkauron',
                 online: false},
                {pseudo: 'cskim13',
                 online: true},
                {pseudo: 'Cryolithius',
                 online: false},
                {pseudo: 'PartyPancakes',
                 online: false},
                {pseudo: 'Dwragon',
                 online: true},
                {pseudo: 'crazydev',
                 online: false},
                {pseudo: 'crazy991',
                 online: true},
                {pseudo: 'Herobrine',
                 online: true},
                {pseudo: 'Hypershadsy',
                 online: false},
                {pseudo: 'CrazyJared',
                 online: false},
                {pseudo: 'Alp',
                 online: true},
                {pseudo: 'coopersnow',
                 online: false},
                {pseudo: 'Dragonite24',
                 online: true},
                {pseudo: 'Mongoloid',
                 online: false},
                {pseudo: 'yoshi8710',
                 online: false},
                {pseudo: 'BowlOfSoup',
                 online: true},
                {pseudo: 'Cheeeezzz',
                 online: true},
                {pseudo: 'SunriseMoon',
                 online: false},
                {pseudo: 'Cheapshot',
                 online: true},
                {pseudo: 'Quex',
                 online: false},
                {pseudo: 'Dr_MadMan',
                 online: true},
                {pseudo: 'jeb_',
                 online: false},
                {pseudo: 'Sogo',
                 online: false},
                {pseudo: 'torteela',
                 online: false},
                {pseudo: 'Dapper_Swain',
                 online: true},
                {pseudo: 'barrowsx',
                 online: false},
                {pseudo: 'HellCatcher',
                 online: true},
                {pseudo: 'brandonhare',
                 online: false},
                {pseudo: 'Apptendo',
                 online: false},
                {pseudo: 'Frewp',
                 online: true},
                {pseudo: 'Hoodoo456',
                 online: true},
                {pseudo: 'Caboose2641',
                 online: true},
                {pseudo: 'lordskelzor',
                 online: false},
                {pseudo: 'wolfenstrike',
                 online: true},
                {pseudo: 'Sukor',
                 online: false},
                {pseudo: 'JakeEpps',
                 online: true},
                {pseudo: 'EpicPoodle',
                 online: false},
                {pseudo: 'Darber',
                 online: false},
                {pseudo: 'DTB1996',
                 online: false},
                {pseudo: 'thebiglebowski33',
                 online: true},
                {pseudo: 'Tinter',
                 online: false},
                {pseudo: 'Computrix',
                 online: true},
                {pseudo: 'pro',
                 online: true},
                {pseudo: 'jake',
                 online: true},
                {pseudo: 'Nazilord24',
                 online: false},
                {pseudo: 'fef',
                 online: false},
                {pseudo: 'auntjoemima',
                 online: true},
                {pseudo: 'Concrete',
                 online: true},
                {pseudo: 'dynemo',
                 online: false},
                {pseudo: 'Sgt_Cortez',
                 online: true},
                {pseudo: 'phabeZ',
                 online: true},
                {pseudo: 'Segolia',
                 online: true},
                {pseudo: 'Jakeiswin',
                 online: true},
                {pseudo: 'Masterlegodude',
                 online: true},
                {pseudo: 'metrotyranno',
                 online: false},
                {pseudo: 'DimJim',
                 online: true},
                {pseudo: 'ChauffeR',
                 online: true},
                {pseudo: 'KingSam',
                 online: false},
                {pseudo: 'richard9311',
                 online: true},
                {pseudo: 'iam2little',
                 online: false},
                {pseudo: 'Lassemb',
                 online: true},
                {pseudo: 'Valdrec',
                 online: false},
                {pseudo: 'zedpenguin',
                 online: true},
                {pseudo: 'kubson',
                 online: false},
                {pseudo: 'cyndrasil',
                 online: false},
                {pseudo: 'Trase',
                 online: false},
                {pseudo: 'Fish_Warden',
                 online: true},
                {pseudo: 'Tuxedo',
                 online: true},
                {pseudo: 'phray',
                 online: true},
                {pseudo: 'gawdofrofls',
                 online: true},
                {pseudo: 'N10do64',
                 online: true},
                {pseudo: 'Grimmy423',
                 online: false},
                {pseudo: 'TPmax17',
                 online: true},
                {pseudo: 'liv3d',
                 online: false},
                {pseudo: 'kizzycocoa',
                 online: false},
                {pseudo: 'Earfull',
                 online: true},
                {pseudo: 'Jexeld',
                 online: true},
                {pseudo: 'Scheer',
                 online: false},
                {pseudo: 'Medlir',
                 online: true},
                {pseudo: 'memnoc',
                 online: true},
                {pseudo: 'Auv5',
                 online: true},
                {pseudo: 'Neath',
                 online: false},
                {pseudo: 'Xylic',
                 online: false},
                {pseudo: 'pr0nstar',
                 online: false},
                {pseudo: 'deadmat',
                 online: true},
                {pseudo: 'citricsquid',
                 online: true},
                {pseudo: 'Conan3D',
                 online: true},
                {pseudo: 'rubbersoul420',
                 online: true},
                {pseudo: 'IvanDonat',
                 online: true},
                {pseudo: 'cheater09',
                 online: false},
                {pseudo: 'Spyder638',
                 online: false},
                {pseudo: '_Undefined',
                 online: true},
                {pseudo: 'andersonmat',
                 online: false},
                {pseudo: 'Rixxz2',
                 online: false},
                {pseudo: 'simix10',
                 online: false},
                {pseudo: 'RedPeepin',
                 online: false},
                {pseudo: 'ejonkou',
                 online: true},
                {pseudo: 'xHellfire',
                 online: false},
                {pseudo: 'AdamtheClown',
                 online: false},
                {pseudo: 'cyrkon',
                 online: true},
                {pseudo: 'Genesis343',
                 online: false},
                {pseudo: 'CapnAwesom',
                 online: true},
                {pseudo: 'SolWolf',
                 online: true},
                {pseudo: 'Neogetz',
                 online: false},
                {pseudo: 'Gotcha',
                 online: false},
                {pseudo: 'nox_PHX',
                 online: false},
                {pseudo: 'Elloa',
                 online: true},
                {pseudo: 'Razorlance',
                 online: false},
                {pseudo: 'whatnow',
                 online: true},
                {pseudo: 'Zuriki',
                 online: true},
                {pseudo: 'Dread',
                 online: false},
                {pseudo: 'Majeh',
                 online: false},
                {pseudo: 'Snowman',
                 online: true},
                {pseudo: 'WOOTinator',
                 online: false},
                {pseudo: 'Pledgemonkey',
                 online: false},
                {pseudo: 'McBeeferton',
                 online: false},
                {pseudo: 'Xephos',
                 online: false},
                {pseudo: 'Honeydew',
                 online: true},
                {pseudo: 'Old_Peculier',
                 online: false},
                {pseudo: 'Israphael',
                 online: false},
                {pseudo: 'Israphel',
                 online: false},
                {pseudo: 'Ryzo',
                 online: true},
                {pseudo: 'Skylord_Lysander',
                 online: false},
                {pseudo: 'Swedman',
                 online: false},
                {pseudo: 'jmcneely',
                 online: false},
                {pseudo: 'lolpie24',
                 online: false},
                {pseudo: 'Xkrules',
                 online: true},
                {pseudo: 'Hollure',
                 online: false},
                {pseudo: 'lonewarrior',
                 online: true},
                {pseudo: 'slubub',
                 online: false},
                {pseudo: 'pinguiniv',
                 online: true},
                {pseudo: 'Demonkush',
                 online: true},
                {pseudo: 'Destati',
                 online: false},
                {pseudo: 'raquzzic2',
                 online: false},
                {pseudo: 'sord213',
                 online: true},
                {pseudo: 'Colten',
                 online: true},
                {pseudo: 'CG62',
                 online: false},
                {pseudo: 'mrwormy',
                 online: false},
                {pseudo: 'Agronaut',
                 online: true},
                {pseudo: 'mikeybx',
                 online: true},
                {pseudo: 'Kakarikon',
                 online: true},
                {pseudo: 'Crazyiness',
                 online: true},
                {pseudo: 'power526',
                 online: true},
                {pseudo: 'SlamBamActionman',
                 online: true},
                {pseudo: 'Yoyosorayo',
                 online: true},
                {pseudo: 'thetaco8808',
                 online: false},
                {pseudo: 'kittyinabottle',
                 online: false},
                {pseudo: 'Jakeobs',
                 online: true},
                {pseudo: 'jctitan',
                 online: true},
                {pseudo: 'kbdasoccer',
                 online: false},
                {pseudo: 'Menen',
                 online: false},
                {pseudo: 'A_Big_Rock',
                 online: false},
                {pseudo: 'Fendron',
                 online: true},
                {pseudo: 'robloxx',
                 online: true},
                {pseudo: 'elbowgrease12',
                 online: false},
                {pseudo: 'stolengoose',
                 online: true},
                {pseudo: 'kafder2',
                 online: false},
                {pseudo: 'Fvpm',
                 online: true},
                {pseudo: 'jnr_cckane',
                 online: true},
                {pseudo: 'kelquethas',
                 online: false},
                {pseudo: 'Zakhep',
                 online: true},
                {pseudo: 'mons10',
                 online: true},
                {pseudo: 'elrobto',
                 online: true},
                {pseudo: 'setsunakai',
                 online: true},
                {pseudo: 'doomplayer',
                 online: false},
                {pseudo: 'Pwnage_HenTgen',
                 online: true},
                {pseudo: 'Rooopppi',
                 online: false},
                {pseudo: 'm00gle',
                 online: true},
                {pseudo: 'Stuu',
                 online: false},
                {pseudo: 'T3hdrakkus',
                 online: true},
                {pseudo: 'MrDerogative',
                 online: false},
                {pseudo: 'Goratrixx',
                 online: false},
                {pseudo: 'Swordself',
                 online: true},
                {pseudo: 'Pelleybelley',
                 online: true},
                {pseudo: 'whitenoize',
                 online: false},
                {pseudo: 'groopo',
                 online: true},
                {pseudo: 'Skype',
                 online: false},
                {pseudo: 'CruelNoise',
                 online: false},
                {pseudo: 'Alphasoldier',
                 online: true},
                {pseudo: 'Whitehman',
                 online: true},
                {pseudo: 'Omicron',
                 online: true},
                {pseudo: 'Olidood',
                 online: false},
                {pseudo: 'ryuanesha',
                 online: true},
                {pseudo: 'MiniMatt',
                 online: true},
                {pseudo: 'DolphinTuna',
                 online: false},
                {pseudo: 'GladeGuard',
                 online: false},
                {pseudo: 'IronValley',
                 online: true},
                {pseudo: 'Shadowtex',
                 online: true},
                {pseudo: 's_amroberts',
                 online: false},
                {pseudo: 'Old_Peculiar',
                 online: true},
                {pseudo: 'Alienation25',
                 online: true},
                {pseudo: 'Blaxor',
                 online: true},
                {pseudo: 'Klegg',
                 online: false},
                {pseudo: 'beth',
                 online: false},
                {pseudo: 'Bomber57',
                 online: true},
                {pseudo: 'GoogleChrome',
                 online: true},
                {pseudo: 'lurkercraft',
                 online: false},
                {pseudo: 'Xcronias',
                 online: true},
                {pseudo: 'Googie2149',
                 online: true},
                {pseudo: 'muncher21',
                 online: true},
                {pseudo: 'Rhyno',
                 online: true},
                {pseudo: 'JorgeZ',
                 online: false},
                {pseudo: 'xilefian',
                 online: true},
                {pseudo: 'Manarine',
                 online: true},
                {pseudo: 'steinhaus',
                 online: true},
                {pseudo: 'Grabarz19',
                 online: true},
                {pseudo: 'Gamer027',
                 online: true},
                {pseudo: 'Glass_Miner',
                 online: false},
                {pseudo: 'Insidiea',
                 online: false},
                {pseudo: 'Helgesander',
                 online: true},
                {pseudo: 'InsanityMan',
                 online: true},
                {pseudo: 'Moonie',
                 online: true},
                {pseudo: 'FreezeInc',
                 online: true},
                {pseudo: 'Dostya',
                 online: true},
                {pseudo: 'Mistrale',
                 online: false},
                {pseudo: 'Dowdoon',
                 online: true},
                {pseudo: 'Smurfffff',
                 online: false},
                {pseudo: 'Duh102',
                 online: false},
                {pseudo: 'minemap',
                 online: true},
                {pseudo: 'Woodenwindows',
                 online: false},
                {pseudo: 'SeanNanoware',
                 online: true},
                {pseudo: 'varunax',
                 online: true},
                {pseudo: 'zdragun',
                 online: true},
                {pseudo: 'Milkcooks',
                 online: false},
                {pseudo: 'nickieroonie',
                 online: false},
                {pseudo: 'ComputerMan12',
                 online: false},
                {pseudo: 'Mr_Conner',
                 online: false},
                {pseudo: 'Gabe_Newell',
                 online: false},
                {pseudo: 'crazymonkay',
                 online: true},
                {pseudo: 'modify',
                 online: false},
                {pseudo: 'TheJohan',
                 online: true},
                {pseudo: 'Twilizer5953',
                 online: true},
                {pseudo: 'Daniel_Rogers',
                 online: false},
                {pseudo: 'spiderfrog',
                 online: true},
                {pseudo: 'EleOnAUni',
                 online: false},
                {pseudo: 'MrBix',
                 online: true},
                {pseudo: 'Bites',
                 online: true},
                {pseudo: 'kinglahcrab',
                 online: false},
                {pseudo: 'SenorStab',
                 online: false},
                {pseudo: 'MasterDucky',
                 online: true},
                {pseudo: 'Gamerx123',
                 online: true},
                {pseudo: 'mules',
                 online: false},
                {pseudo: 'Joe',
                 online: false},
                {pseudo: 'daaaaaan',
                 online: false},
                {pseudo: 'iDP',
                 online: true},
                {pseudo: 'HappyHappyMan',
                 online: false},
                {pseudo: 'DwarfWoot',
                 online: true},
                {pseudo: 'puddin1',
                 online: true},
                {pseudo: 'cavo94',
                 online: true},
                {pseudo: 'got_milk4',
                 online: true},
                {pseudo: 'Tawtle',
                 online: false},
                {pseudo: 'stupib',
                 online: false},
                {pseudo: 'Satele',
                 online: false},
                {pseudo: 'GhostlyGob',
                 online: true},
                {pseudo: 'cheetum',
                 online: true},
                {pseudo: 'ssojj',
                 online: true},
                {pseudo: 'The_Noodle',
                 online: true},
                {pseudo: 'Huseeee',
                 online: true},
                {pseudo: 'subtraho',
                 online: true},
                {pseudo: 'horsedrowner',
                 online: false},
                {pseudo: 'WafflesMgee',
                 online: false},
                {pseudo: 'Halofannr1',
                 online: false},
                {pseudo: 'FlashFireSix',
                 online: true},
                {pseudo: 'CowThing',
                 online: true},
                {pseudo: 'GinTheNinja',
                 online: true},
                {pseudo: 'eLIR',
                 online: true},
                {pseudo: 'BearzUnlimited',
                 online: true},
                {pseudo: 'Beavis9563',
                 online: true},
                {pseudo: 'Pyronaught41',
                 online: false},
                {pseudo: 'Wido',
                 online: false},
                {pseudo: 'Eisblut',
                 online: true},
                {pseudo: 'coolkid588',
                 online: false},
                {pseudo: 'Rex_Rex',
                 online: true},
                {pseudo: 'TTsands',
                 online: false},
                {pseudo: 'jakers247',
                 online: false},
                {pseudo: 'Mr_Hedra',
                 online: true},
                {pseudo: 'Clavus',
                 online: false},
                {pseudo: 'Minecrafter12335',
                 online: true},
                {pseudo: 'agnl',
                 online: true},
                {pseudo: 'Nerdrage',
                 online: true},
                {pseudo: '00Fraday00',
                 online: true},
                {pseudo: 'CaptainQuirk73',
                 online: true},
                {pseudo: 'Naut314',
                 online: false},
                {pseudo: 'Zombie_Boss',
                 online: true},
                {pseudo: 'Creeper_Boss',
                 online: true},
                {pseudo: 'Pricex3',
                 online: false},
                {pseudo: 'Divran',
                 online: true},
                {pseudo: 'Ket',
                 online: false},
                {pseudo: 'Astrellon',
                 online: true},
                {pseudo: 'Bisyss',
                 online: false},
                {pseudo: 'scarletbanner',
                 online: false},
                {pseudo: 'bluelive',
                 online: false},
                {pseudo: 'workbench',
                 online: false},
                {pseudo: 'L_NK',
                 online: false},
                {pseudo: 'Striata',
                 online: false},
                {pseudo: 'Gabbeh',
                 online: false},
                {pseudo: 'mendo89',
                 online: true},
                {pseudo: 'valakut',
                 online: true},
                {pseudo: 'nakedlightbulbs',
                 online: false},
                {pseudo: 'masterbetty',
                 online: true},
                {pseudo: 'prichards',
                 online: false},
                {pseudo: 'atliax',
                 online: true},
                {pseudo: 'drtaru',
                 online: false},
                {pseudo: 'adnan252',
                 online: false},
                {pseudo: 'nikondork',
                 online: false},
                {pseudo: 'OttoKatz',
                 online: false}];
var serversID = [];
var playersID = [];
var statsServer = [];
var createServers = function(serverKey, callback) {
  Server.create(servers[serverKey]).exec(function(err, server) {
    if(err) { console.log(err) }
    serversID[serverKey] = server.id;
    serverKey += 1;
    if(serverKey < servers.length) {
      createServers(serverKey, callback);
    }
    else {
      console.log("Server collection populated !");
      createPlayers(0);
    }
  });
};

var createPlayers = function(playerKey, callback) {
  Player.create(players[playerKey]).exec(function(err, player) {
    if(err) { console.log(err) }
    var srv = [];
    var rndServersCounter = Math.floor((Math.random()*(servers.length/2)));
    if(rndServersCounter === 0) { rndServersCounter = 1 }
    while(rndServersCounter > 0) {
      var rndServersId = Math.floor((Math.random()*(servers.length-1)));
      srv.push(serversID[rndServersId]);
      player.servers.push(serversID[rndServersId]);
      rndServersCounter--;
    }
    statsServer[playerKey] = srv;
    player.save(function(err) {
      if(err) { console.log(err) }
      playersID[playerKey] = player.id;
      playerKey += 1;
      if(playerKey < players.length) {
        createPlayers(playerKey, callback);
      }
      else {
        console.log("Player collection populated !");
        createStats(0);
      }
    });
  });
};

var createStats = function(playerKey, callback) {
  for(statsServerKey in statsServer[playerKey]) {
    PlayerStat.create({player: playersID[playerKey], server: serversID[statsServerKey], ratio: 0, timePlayed: Math.floor((Math.random()*604800)), blocksBroken: Math.floor((Math.random()*10000)), blocksPlaced: Math.floor((Math.random()*10000)), levelMax: Math.floor((Math.random()*50)), verbosity: Math.floor((Math.random()*10000)), kills: 0, pvpDeaths: 0, stupidDeaths: Math.floor((Math.random()*1000))}).exec(function (err, stats) {
      if(err) { console.log(err) }
    })
  }

  playerKey += 1;
  if(playerKey < players.length) {
    createStats(playerKey, callback);
  }
  else {
    console.log("Stats collection populated !");
    createKills(0);
  }
};

var createKills = function(playerKey, callback) {
  rndKillsCounter = Math.floor((Math.random()*100));
  while(rndKillsCounter > 0) {
    rndVictim = Math.floor((Math.random()*(playersID.length-1)));
    rndServer = Math.floor((Math.random()*(statsServer[playerKey].length-1)));
    Kill.create({killed: playersID[rndVictim], killer: playersID[playerKey], server: statsServer[playerKey][rndServer], weapon: 'SWORD'}).exec(function (err, kill) {
      if(err) { console.log(err) }
    });
    rndKillsCounter--;
  }
  playerKey += 1;
  if(playerKey < players.length) {
    createKills(playerKey, callback);
  }
  else {
    console.log("Kills collection populated !");
  }
};

module.exports = {

  // Handle a plugin connection
  populate: function(req, res) {
    createServers(0);

    res.send("Populating the database...<br/>Check your console to be aware of errors");
  },

  /**
   * Overrides for the settings in `config/controllers.js`
   * (specific to APIController)
   */
  _config: {}


};
